// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQzP2xVtJO-6MHw2ksnCLZLhVUcLEL1kM',
    appId: '1:518782018674:web:b9f7f0084f4c1f93b74eeb',
    messagingSenderId: '518782018674',
    projectId: 'todo-c932d',
    authDomain: 'todo-c932d.firebaseapp.com',
    storageBucket: 'todo-c932d.appspot.com',
    measurementId: 'G-6C7DMLBFQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1VFNaR-S-qaPZYzmrRhKzNB7WXdgU8Oo',
    appId: '1:518782018674:android:2f39fe7708a43dbbb74eeb',
    messagingSenderId: '518782018674',
    projectId: 'todo-c932d',
    storageBucket: 'todo-c932d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnCzXu5f_1ItlXLAzwHApaVRjnm83C2jM',
    appId: '1:518782018674:ios:541811b8d7d516f3b74eeb',
    messagingSenderId: '518782018674',
    projectId: 'todo-c932d',
    storageBucket: 'todo-c932d.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnCzXu5f_1ItlXLAzwHApaVRjnm83C2jM',
    appId: '1:518782018674:ios:5e71d352116df1f9b74eeb',
    messagingSenderId: '518782018674',
    projectId: 'todo-c932d',
    storageBucket: 'todo-c932d.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
